name: airbnb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=75.1
  - joblib=1.5.1
  - khronos-opencl-icd-loader=2024.10.24
  - libblas=3.11.0
  - libboost=1.88.0
  - libcblas=3.11.0
  - libcxx=21.1.7
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=21.1.7
  - ncurses=6.5
  - opencl-headers=2025.06.13
  - openssl=3.6.0
  - packaging=25.0
  - patsy=1.0.1
  - pip=25.1.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - readline=8.2
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==3.7.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - catboost==1.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - fastapi==0.104.1
      - fonttools==4.60.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - h11==0.16.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - narwhals==2.13.0
      - numpy==1.24.3
      - pandas==2.1.3
      - pillow==11.3.0
      - plotly==5.18.0
      - protobuf==6.33.2
      - pyarrow==21.0.0
      - pydantic==2.5.0
      - pydantic-core==2.14.1
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-multipart==0.0.6
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - scikit-learn==1.3.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.27.0
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.3
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - uvicorn==0.24.0
      - xgboost==2.0.2
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/airbnb_env
